name: ${SYSTEM_NAME}

services:

  app:
    image: esrii/${SYSTEM_NAME}
    container_name: ${SYSTEM_NAME}
    build:
      context: .
    env_file:
      - .env
    expose:
      - "80"
    volumes:
      - ./public_html:/var/www/html
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always

networks:
  default:
    name: webproxy
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
